### ISSUE TITLE
Works with general and random but not other channels

### ISSUE THREAD

**Issue by BoD** [ErikKalkoken/slackchannel2pdf#4]
Hi! For some reason I'm getting `(1/1) ERROR: Unknown channel '<channel name>' on <workspace>` for all channels except general and random. 

Any idea what the problem could be?

Thanks!

**Comment by BoD** [comment]
After digging a bit, the cause is [the `conversations.list` call](https://api.slack.com/methods/conversations.list#arg_limit) is paginated, with a default value of 100 results. On a big workspace this won't be enough. A simplistic workaround is to increase the limit to the max allowed value of 1000 (the real fix would be to call all the pages in a loop).

In `slackchannel2pdf`, line 298:
```diff
        print("Fetching channels for workspace...")
        response = self._client.conversations_list(
-            types="public_channel,private_channel"
+            types="public_channel,private_channel", limit=1000
        )
```

**Comment by maziman84** [comment]
I have the same issue, how do chage it when I installed the app with pip3 and I can only find /usr/local/bin/slackchannel2pdf which has only few lines?

**Comment by maziman84** [comment]
FYI @ErikKalkoken 
I believe it is not only due to limit, I found out some channels (private or public) work and some not. It might be connected to another reported issue that is not resolved.

**Comment by BoD** [comment]
If you have more than 1000 channels this wouldn't work.

**Comment by maziman84** [comment]
I am testing this script on development workspace so i believe it has much less than 1000. How can I find out total channels?
Anyway, as I said the script works on this workspace on some channels while it does not on some other channels.

**Comment by ErikKalkoken** [comment]
Thanks guys for reporting this issue and for the analysis. I will look into this shortly.
@maziman84 Can you by any chance make out a pattern on what channels work and which don't?

**Comment by maziman84** [comment]
I tried to check all channel I am subscribed to but did not see any pattern tbh. 
I have ony one private channel and it does not work there and like 10 public and it works on most of them but not all. Is there a limit for people in the channel or number of threads or anything like that?

**Comment by ErikKalkoken** [comment]
I see. 
Do you get the exact same error message or something else?
Don't believe that there is a hard limit for member of channels of threads, but it's been a while I wrote this, so I will double check.
But, this app does not work for direct messages and multi direct message channels. So if you have problems with those, that is not a bug.

**Comment by maziman84** [comment]
Same error message every single time. I dont intend to use it for DMs, only want to export channel history. My intention is to export it to Jira or Confluence and this is the best way I found :-)
I have opened new issue 2 days ago for adding timestamps for every message in threads also, can you possibly work on that too please?

**Comment by ErikKalkoken** [comment]
> Same error message every single time. I dont intend to use it for DMs, only want to export channel history.

ok. Might be caused by the same bug then.

> My intention is to export the history to Jira or Confluence and this is the best I found so far :-) is there a way to have different format for easier transport to those tools?

Thanks!. This app has been made primarily to allow exports in PDF. I can currently not commit to adding any additional formats.

> I have opened new issue 2 days ago for adding timestamps for every message in threads also, can you possibly work on that too please?

Sure thing. I will work on fixing the channels paging bug first and then look at the other bug too.

**Comment by ErikKalkoken** [comment]
I have deployed  a new version that has a fix for the missing paging of channel names.
@BoD Could you please check if this fixes your issue?

**Comment by maziman84** [comment]
Issue seems to be resolved, thank you.
However, there is quite enough page fetching even-though the testing channel is empty or very short:
```
Fetching workspace info from Slack...
Fetching users for workspace...
Fetching channels for workspace...
conversations_list - Fetching page 1
...
conversations_list - Fetching page 27
Fetching usergroups for workspace...
Fetching user info for author...
```
Always 27 page fetching.

**Comment by ErikKalkoken** [comment]
Thanks for the feedback.
How many messages do you have in that channel?

**Comment by maziman84** [comment]
One message with 5 messages within thread. I created the channel purely for testing. 
When I checked with other channels the same 27 page fetching happened.

**Comment by ErikKalkoken** [comment]
I see. Yeah that does look like a new bug.

**Comment by ErikKalkoken** [comment]
oh wait. the app is fetching 27 pages from the list of channels, not the channel itself. How many channels do you have?

**Comment by maziman84** [comment]
Honestly I have no idea. Do you how to check if I am not an admin?

**Comment by ErikKalkoken** [comment]
ok. no worries. I will deploy a new version shortly, that will print out the number of found channels. 
We also have a rather small page size in the current version, which I will double so the app to has to fetch less pages.

**Comment by ErikKalkoken** [comment]
This has been fixed with Version 1.2.3

**Comment by Xarlos89** [comment]
Issue still exists for me in 1.3.1 however I identified the issue.

`def _fetch_channel_names(self):
        """returns dict of channel names with channel ID as key"""
        
        # make sure slack client is set
        assert self._client is not None
        
        print("Fetching channels for workspace...")
        response = self._client.conversations_list(
            types="public_channel, private_channel" , limit=10000
            )
        assert response["ok"]    
        channel_names = reduce_to_dict(
            response["channels"], 
            "id", 
            "name"
            )        
        for channel in channel_names:
            print(channel_names[channel])
            # print(channel)
            channel_names[channel] = self._transform_encoding(
                channel_names[channel]
                )
        
        return channel_names`
In this function, in the line     types="public_channel, private_channel" , limit=10000

Removing "public channel" allows you to see all private channels, so evidently this arg is not correct and is only taking the first arg. 
Quickfix is removing 'public_channel' and running.

**Comment by ErikKalkoken** [comment]
Also, looking at the documentation I just noticed, that the limit can not be larger than 1.000. So you would run into this problem already with a couple of hundred channels. 

I think the real fix would be to implement proper paging, so that more than 1.000 channels can be pulled. I will look into it.

**Comment by ErikKalkoken** [comment]
@Xarlos89 
I have not worked with this code for month, but looking at it again today I realized that I have implemented paging for fetching channels (and other objects) a long time ago. The code you are referring to above is outdated.

This is the same location in the new code:

https://github.com/ErikKalkoken/slackchannel2pdf/blob/f050a6458bf035171c1ed3a01d06d727287559a7/slackchannel2pdf/slack_service.py#L119

Please update to the newest version and try again. The new version has no technical upper limit for the amount of channels it can fetch.

Closing this as fixed.
