### ISSUE TITLE
Missing timestamp for posts in thread

### ISSUE THREAD

**Issue by maziman84** [ErikKalkoken/slackchannel2pdf#5]
Is it possible to include timestamps for posts in threads? There is only timestamp for first post in thread.

**Comment by ErikKalkoken** [comment]
Thanks for reporting this bug. I will work on a fix shortly.

**Comment by ErikKalkoken** [comment]
Should be fixed with newest version 1.2.1.
Would be awesome if you could test with the new version and give me feedback if it works for you.
https://pypi.org/project/slackchannel2pdf/1.2.1/

**Comment by maziman84** [comment]
Getting error when run:
```
Traceback (most recent call last):
  File "/usr/local/bin/slackchannel2pdf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/slackchannel2pdf/run.py", line 83, in main
    exporter = SlackChannelExporter(
  File "/usr/local/lib/python3.9/site-packages/slackchannel2pdf/channel_exporter.py", line 56, in __init__
    self._slack_service = SlackService(slack_token)
  File "/usr/local/lib/python3.9/site-packages/slackchannel2pdf/slack_service.py", line 25, in __init__
    locale_helper = LocaleHelper()
  File "/usr/local/lib/python3.9/site-packages/slackchannel2pdf/helpers.py", line 80, in __init__
    print(f"Locale is: {my_locale.get_display_name()} [{my_locale}]")
AttributeError: 'NoneType' object has no attribute 'get_display_name'
```

**Comment by ErikKalkoken** [comment]
Thanks for the quick feedback. I will look into fixing this new bug right away.

**Comment by ErikKalkoken** [comment]
I fixed the bug you reported and releases a new version with the bugfix: https://pypi.org/project/slackchannel2pdf/1.2.2/
Could you please check if the new version works for you?

**Comment by maziman84** [comment]
Started promising but failed later:

slackchannel2pdf v1.2.2 by Erik Kalkoken

```
Fetching workspace info from Slack...
Fetching users from Slack
Fetching users from Slack - page 2
...
Fetching users from Slack - page 7
Fetching users from Slack - page 8
Received a total of 1,421 users
Fetching channels from Slack
Fetching channels from Slack - page 2
...
Fetching channels from Slack - page 14
Received a total of 2,535 channels
Fetching usergroups from Slack...
Traceback (most recent call last):
  File "/usr/local/bin/slackchannel2pdf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/slackchannel2pdf/run.py", line 83, in main
    exporter = SlackChannelExporter(
  File "/usr/local/lib/python3.8/site-packages/slackchannel2pdf/channel_exporter.py", line 56, in __init__
    self._slack_service = SlackService(slack_token)
  File "/usr/local/lib/python3.8/site-packages/slackchannel2pdf/slack_service.py", line 31, in __init__
    self._usergroup_names = self._fetch_usergroup_names()
  File "/usr/local/lib/python3.8/site-packages/slackchannel2pdf/slack_service.py", line 138, in _fetch_usergroup_names
    f"Got a total of "
  File "/usr/local/lib/python3.8/site-packages/babel/numbers.py", line 353, in format_number
    return format_decimal(number, locale=locale)
  File "/usr/local/lib/python3.8/site-packages/babel/numbers.py", line 413, in format_decimal
    format = locale.decimal_formats.get(format)
AttributeError: 'NoneType' object has no attribute 'decimal_formats'
```

**Comment by ErikKalkoken** [comment]
My apologizes this is still not working correctly. 

This looks like it fails in the babel library, because it can not determine a default locale. This is unexpected, but I should be able to work around it.

I have been running this app on both Linux and Windows, but could not reproduce this behavior. Out of curiosity: In which environment are you running the app?

**Comment by ErikKalkoken** [comment]
Here is the new version that should fix the latest bug. Please let me know if this works for you:
https://pypi.org/project/slackchannel2pdf/1.2.3/

**Comment by maziman84** [comment]
MacOS :-) with latest python 3.9.
Will update it later today and provide feedback. Thanks for the updates!

**Comment by maziman84** [comment]
Tried it right away :-D works like a charm! is there an option to hide all the INFO lines and get only result now that it works?

**Comment by ErikKalkoken** [comment]
Glad to hear that it finally works. Thanks for the environment info. Your issue might be related to Python 3.9; I will test that later.

There is no option currently for hiding the info logging, but I can look into that.

**Comment by maziman84** [comment]
I was maybe too fast to confirm it works, as I meant that the script itself works. Checking the pdf exported it looks better as there are more timestamps but it is still buggy as not every post has its own timestamp. As you can see in screenshots the pdf says several posts were done at the same time while there were differences. Hope it is understandable.
<img width="202" alt="Screenshot 2021-02-04 at 20 55 11" src="https://user-images.githubusercontent.com/15727395/106948053-8a829380-672b-11eb-8c7c-b6e47f69116a.png">
<img width="313" alt="Screenshot 2021-02-04 at 20 55 03" src="https://user-images.githubusercontent.com/15727395/106948063-8ce4ed80-672b-11eb-8619-35f985b26336.png">

**Comment by ErikKalkoken** [comment]
Thanks for the additional feedback. I will look into it.

**Comment by ErikKalkoken** [comment]
Yeah, this was a bug since you can indeed not distinguish between posts from different dates. 
I released an update that should address that. Please have a look: https://pypi.org/project/slackchannel2pdf/1.2.4/

**Comment by maziman84** [comment]
Unfortunately I don't see any improvement. Output looks exactly the same.

**Comment by maziman84** [comment]
@ErikKalkoken can you check why the timestamps are still not visible for all messages please?

**Comment by ErikKalkoken** [comment]
Sorry, I was busy with other projects the last days.

The app is not showing timestamps on subsequent messages from the same user within 10 minutes. Similar to how the Slack client works. This is not a bug.

Previous to my last patch that did not work for thread messages, but it does now.

If you still see an issue, could you please describe in detail what that is?

**Comment by maziman84** [comment]
Oh, so it is a feature, damn. My question/request is, can you make it to post timestamp to "every" message not like Slack does it?

**Comment by ErikKalkoken** [comment]
ok, no problem. I can add a configuration for that behavior.

**Comment by ErikKalkoken** [comment]
As promised I added a configuration option so you can have time shown for every post. To make this happen you need to create a configuration file and set `minutes_until_username_repeats = 0` in the section `[slack]`. Please see the section about configurations in the README for details.

The new version also does no longer show progress details by default as you requested.

I will release this new version as alpha for now and would appreciate your feedback on how well this works for you.

https://pypi.org/project/slackchannel2pdf/1.3.0a1/

**Comment by maziman84** [comment]
Works as requested 👍 Thank you Erik
I could not find the ini config file by default anywhere so had to download the Code in zip, copied to /usr/local/lib/python3.9/site-packages/slackchannel2pdf/ and changed the setting from 10 to 0.
If I want to see the progress details, what do I have to change?

**Comment by ErikKalkoken** [comment]
> I could not find the ini config file by default anywhere
OK. that should not happen. Let me look into that.
> If I want to see the progress details, what do I have to change?
Just `set console_log_level` to info

**Comment by ErikKalkoken** [comment]
Fixed in new version: https://pypi.org/project/slackchannel2pdf/1.3.0a2/

Note that the new version will automatically install the default config file in your Python environment. You may therefore want to copy your existing file to your home directory before running the update, or it might be overwritten.

**Comment by maziman84** [comment]
Problem solved, tested and works just fine. Thank you very much for all the help with requests Erik! Much appreciated.

**Comment by ErikKalkoken** [comment]
Awesome! 

Thank you too, for your patience and for your great help in improving this app. 

I will now close this issue. But please feel free to open a new issue if you have any additional requests /ideas on how to further improve slackchannel2pdf.
